server:
  port: 8090

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/fixDB
    username: postgres
    password: 123
    driverClassName: org.postgresql.Driver

