server:
  port: 8080

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/testDB
    username: postgres
    password: 123
    driverClassName: org.postgresql.Driver

  kafka:
    consumer:
      auto-offset-reset: earliest
